disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    
line_length: 200

identifier_name:
  excluded:
    - vc
    - id
    - ID
    

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
